# Generated by Django 5.0.2 on 2024-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingfood',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
