# Generated by Django 5.0.2 on 2024-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда:')),
                ('description', models.TextField(verbose_name='Описание блюда:')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты:')),
                ('steps', models.TextField(verbose_name='Последовательность приготовления:')),
                ('price', models.PositiveIntegerField(verbose_name='Примерная стоимость:')),
                ('image', models.URLField(verbose_name='Ссылка на изображение:')),
                ('time_cook', models.PositiveIntegerField(verbose_name='Время готовки:')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность приготовления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
