# Generated by Django 5.0.2 on 2024-03-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_book', '0003_rename_reviesrecipes_reviewsrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, null=True, verbose_name='Сложность приготовления'),
        ),
        migrations.DeleteModel(
            name='ReviewsRecipes',
        ),
    ]
